name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  # https://github.com/marketplace/actions/build-tag-number
  # Increase version ${{needs.job1.outputs.build_number}}
  version_increase:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.actions_token}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"


  setup_history:
    name: Checkout, Gradle caches and JDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2
      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

  validate_gradle:
    name: Validate gradle
    runs-on: ubuntu-latest
    needs: setup_history
    steps:
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

  build:
    name: Build and upload
    runs-on: ubuntu-latest
    # ${{needs.version_increase.outputs.build_number}}
    needs: [ version_increase, validate_gradle, setup_history ]
    steps:
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew shadowJar --stacktrace
      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@v3
        with:
          name: JVMGithubActions-Package
          path: ./jars
